version: '3.7'
services:
  ubuntu:
    image: ubuntu:last
    command: tail -f /dev/null
    volumes:
      - data:/data
    ports:
      - "22:22"
    environment:
      - USERNAME=root
      - PASSWORD=root
volumes:
  data:
